### ISSUE TITLE
Amélioration du module

### ISSUE THREAD

**Issue by yoyo770** [comur/ComurImageBundle#99] opened 2017-05-08 14:46 UTC
Hello,

I use your module which is pretty well done, but I notice several things to improve as well as several bug.

Improvement:

1. You can not upload multiple images at the same time.
2. The image movement is not adapted to the tactile support.
3. Images are not removed from the server when it is removed from the server.
4. the images are too heavy and duplicate in several files (cropped ...) would have to think to reduce the weight of the images

Bug:
1. When I put multiple forms with this system on the same page, you can not move the images correctly.
2. With several forms when closing the popup and reopening it in another form it keeps the photos selected in the 1st form.
3. The load bar does not fade when the load is finished.
4. sometimes the picture does not appear (when the picture is too heavy.

Cordially.
I am at your disposal if you need help.

**Comment by comur** [comment] 2018-07-19 07:15
Hi @yoyo770 
Thanks for the list
I thing there are some more I can add to this list but the problem is I never have time to add any improvement so as you purpose your help I can only accept it.
Would you create a first PR to correct some of bugs ?
Thanks

**Comment by yoyo770** [comment] 2018-07-20 06:40
Bonjour,

Ce bundle est le seule que j'ai pu trouver qui gere bien les galeries d'image sur symfony. ce serait vraiment dommage de le laisser a l'abandon. en ce moment je n'ai pas beaucoup de temps de disponible. Mais dès que je peux je vous enverrez des correctifs.

Merci.



Envoyé de mon Galaxy S7 edge Orange

-------- Message d'origine --------
De : Can OMUR <notifications@github.com>
Date : 19/07/2018 09:15 (GMT+01:00)
À : comur/ComurImageBundle <ComurImageBundle@noreply.github.com>
Cc : yoyo770 <yossicohen@hotmail.fr>, Mention <mention@noreply.github.com>
Objet : Re: [comur/ComurImageBundle] Amélioration du module (#99)


Hi @yoyo770<https://github.com/yoyo770>
Thanks for the list
I thing there are some more I can add to this list but the problem is I never have time to add any improvement so as you purpose your help I can only accept it.
Would you create a first PR to correct some of bugs ?
Thanks

**Comment by comur** [comment] 2018-07-20 09:12
Bonjour,

Merci.

Can OMUR
omur.can@gmail.com
+33 (0)6.79.66.58.28

2018-07-20 8:40 GMT+02:00 yoyo770 <notifications@github.com>:

**Comment by comur** [comment] 2019-05-23 14:09
I close this issue, please open a new one if you need

**Closed by comur** 2019-05-23 14:09 UTC
