### ISSUE TITLE
Uncaught SyntaxError: Unexpected token x

### ISSUE THREAD

**Issue by adityarai** [comur/ComurImageBundle#35] opened 2015-02-04 08:13 UTC
shows error - Uncaught SyntaxError: Unexpected token x - when i click edit button,.. i think it has to do something with parseJson

**Comment by comur** [comment] 2015-02-04 09:26
Hi @adityarai 

Can you give me some more info ?
Which branch you use and which version of bootstrap you have ?
Is it a javascript error ? Can you look at inspector and give me some more info (file names and line that error occurs) ?

**Comment by comur** [comment] 2015-02-24 15:25
I close this issue, if you have more info to give me, you can reopen it.

**Closed by comur** 2015-02-24 15:25 UTC

**Comment by yannbenichou** [comment] 2015-04-12 09:33
Hello i having the same problem: "Uncaught SyntaxError: Unexpected token i" when I click on the "Edit" button where I included the image widget.

 I use the branch :  "comur/image-bundle": "1.0.*@dev"
and bootstrap 3.

In my layout I used {% include "ComurImageBundle:Form:croppable_image_modal.html.twig" with {'include_jquery': false, 'include_bootstrap': false} %} since i'm already including a jquery script and bootstrap 3. I made sure the include was after the jquery script.

When i click on the error msg in the navigator console. i don't get a specific line number, so i have no idea where the error is coming from.

**Comment by evuez** [comment] 2015-04-12 11:45
The issue is due to some escaping madness with windows paths...
So in [CroppableImageType#101](https://github.com/comur/ComurImageBundle/blob/e4947e244c17ef902e3ffd1810de5acfb181c866/Form/Type/CroppableImageType.php#L101) if your path looks like ```C:\\www\\uploads\\...```, it won't work and instead you'll have to double-escape every backslashes so that it looks like that: ```C:\\\\www\\\\uploads\\\\...```.

And the error happen when the ```$.parseJSON``` in [fields.html.twig](https://github.com/comur/ComurImageBundle/blob/c8c4957e9114a664476143880d42058fdfcd7e55/Resources/views/Form/fields.html.twig#L55) tries to parse the path, because the Javascript ```\\``` will evaluate to ```\``` instead of a ```\\``` required for the JSON to be valid.
